dist: xenial
sudo: required
os: linux

language: python
python: 3.7

# list packages installable using apt here
addons:
    apt:
        packages:
            - python3-setuptools
            - python3-pip
            - libasound2-dev
            - socat

# requires that commit is for a PR or is on master branch
if : (type = pull_request) OR (type = push AND branch = master)

jobs:
    include:
        - name: test
          script:
            - echo "testing"

        - name: format
          script:
            - echo "formatting"

        - name: build
          script:
            - echo "building"
